services:
    db:
        image: postgres:16.2
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=django
            - POSTGRES_USER=django
            - POSTGRES_PASSWORD=django
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U django"]
            interval: 10s
            timeout: 5s
            retries: 5

    web:
        build:
            context: .
            dockerfile: Dockerfile-local
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
            
            
        restart: on-failure:1
        env_file:
            -   .env

    frontend:
        image: node:23-slim  # Using the slim variant
        working_dir: /app/frontend
        volumes:
            - .:/app
        command: bash -c "npm install && npm run dev"
        environment:
            - ROLLUP_SKIP_NODE_RESOLUTION=true
            - NODE_OPTIONS=--max-old-space-size=4096
        ports:
            - "5173:5173"

    procrastinate-worker:
        build:
            context: .
            dockerfile: Dockerfile-local
        command: "python manage.py procrastinate worker"
        volumes:
            - .:/app
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env

volumes:
    postgres_data:
