# Generated by Django 5.0.4 on 2024-05-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="avatar",
        ),
    ]
