# Generated by Django 5.0.8 on 2024-08-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="module",
            field=models.BooleanField(default=False),
        ),
    ]
