# Generated by Django 5.1.6 on 2025-03-01 05:34

import django.db.models.manager
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_report_options_remove_report_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "channel_id",
                    models.CharField(
                        choices=[],
                        help_text="Discord channel ID to send the announcement to.",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        choices=[
                            (3447003, "Blue"),
                            (16734003, "Orange"),
                            (2600544, "Green"),
                            (15158332, "Red"),
                            (10181046, "Purple"),
                        ],
                        default=3447003,
                        help_text="Color for the Discord embed sidebar.",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to make the title clickable.",
                        null=True,
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        default="LanguageLoom | Connect and Learn",
                        help_text="Text to appear in the footer of the Discord embed.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Discord Announcement",
                "verbose_name_plural": "Discord Announcements",
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
